// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"QuasiMovements","status":true,"description":"v1.299\nChange the way RPG Maker MV handles Movement.\n<QuasiMovement>","parameters":{"Grid":"1","Off Grid":"true","Tile Size":"48","=====================":"","Smart Move":"0","Old Smart Move Dir":"false","Mid Pass":"false","Move On Click":"false","Diagonal":"false","Diagonal Speed":"0","Collision":"#ff0000","Water Collision":"#00ff00","Deep Water Collision":"#0000ff","Collision Map Scan":"4","Water Terrain Tag":"1","Deep Water Terrain Tag":"2","Player Box":"36, 24, 6, 24","Event Box":"36, 24, 6, 24","Boat Box":"36, 24, 6, 12","Ship Box":"36, 24, 6, 24","Airship Box":"36, 36, 6, 6","JSON folder":"data/","Collision Map folder":"img/parallaxes/","Region Map folder":"img/parallaxes/","Use Regions Boxes":"false","Show Boxes":"true","Draw Tile Boxes":"true","Cache Colliders as Bitmap":"true"}},
{"name":"OrangeCustomEvents","status":true,"description":"This plugin Will let you add or copy events to the current map","parameters":{}},
{"name":"OrangeCustomEventCreator","status":true,"description":"This plugin Will let you create virtual events with script calls","parameters":{}},
{"name":"MMO","status":true,"description":"MMORPG plugin","parameters":{}},
{"name":"MMO_Characters_Moves","status":true,"description":"MMORPG plugin","parameters":{}},
{"name":"MMO_ChatBox","status":true,"description":"Chatbox form","parameters":{}},
{"name":"MMO_LoginForm _Bis","status":false,"description":"Login form","parameters":{}},
{"name":"MMO_LoginForm","status":true,"description":"Login form","parameters":{}}
];
