// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OrangeCustomEvents","status":true,"description":"This plugin Will let you add or copy events to the current map","parameters":{}},
{"name":"MMO_OrangeCustomEventCreator","status":true,"description":"This plugin Will let you create virtual events with script calls","parameters":{}},
{"name":"MMO_Core","status":true,"description":"MMORPG Maker MV - Core","parameters":{"Server Location":"http://127.0.0.1:8097/"}},
{"name":"MMO_Core_Player","status":true,"description":"MMORPG Maker MV - Core Handling Player","parameters":{"Mouse Movements":"false","Use Native Respawn":"false"}},
{"name":"MMO_Core_Players","status":true,"description":"MMORPG Maker MV - Core Handling Players","parameters":{}},
{"name":"MMO_Core_Party","status":true,"description":"MMORPG Maker MV - Core Handling Parties","parameters":{}},
{"name":"MMO_Core_Party_Combat","status":true,"description":"MMORPG Maker MV - Core Handling Combat in Party","parameters":{}},
{"name":"MMO_ChatBox","status":true,"description":"MMORPG Maker MV - ChatBox","parameters":{"chatPosition":"TOP LEFT"}},
{"name":"MMO_LoginForm","status":true,"description":"MMORPG Maker MV - Login Form","parameters":{}},
{"name":"MMO_Overhead","status":true,"description":"Add name over actors name","parameters":{}},
{"name":"MMO_iavra_event_popup","status":true,"description":"Allows to display popups messages above events, which can be used for speech bubbles or on chests.\r\n<Iavra Event Popup>","parameters":{"Popup Width":"200","Offset X":"0","Offset Y":"0","Display Duration":"200","Fade In Duration":"10","Fade Out Duration":"60","Font Name":"","Font Size":"12","Line Height":"18","Retain On Scene":"Scene_Menu, Scene_Battle\r"}},
{"name":"MMO_ServerSideMaps","status":false,"description":"MMORPG Maker MV - Server Side Maps","parameters":{}},
{"name":"CacheOverride","status":false,"description":"This allows to force users to re-load old files","parameters":{"gameVersion":"1.0.0"}}
];
